const paths = [
  "/",
  "/clients",
  "/clients/new_visit",
  "/clients/new_subscription",
  "/clients/new_accounting_entry",
  "/clients/edit",
  "/cards",
  "/cards/edit",
  "/visits",
  "/visits/new",
  "/visits/edit",
  "/visits/delete",
  "/subscriptions",
  "/subscriptions/new",
  "/subscriptions/edit",
  "/subscriptions/delete",
  "/costs",
  "/accounting_entries",
  "/accounting_entries/new",
  "/accounting_entries/edit",
  "/accounting_entries/delete",
  "/reservations",
  "/reservations/new",
  "/reservations/edit",
  "/reservations/delete",
  "/forms",
  "/forms/process",
  "/scanner",
  "/calculator",
  "/tariff/visit",
  "/tariff/visit/new",
  "/tariff/visit/edit",
  "/tariff/visit/delete",
  "/tariff/subscription",
  "/tariff/subscription/new",
  "/tariff/subscription/edit",
  "/tariff/subscription/delete",
  "/tariff/reservation",
  "/tariff/reservation/new",
  "/tariff/reservation/edit",
  "/tariff/reservation/delete",
];

export default paths;
  